### ISSUE TITLE
issue env  when run deploy

### ISSUE THREAD

**Issue by thenewspacesky5456** [wan2land/serverless-nuxt#102]
Hello @wan2land 
I have an issue:
process.env.GOOGLE_TAG_MANAGER_ID and process.env.FACEBOOK_PIXEL_ID return NULL value when run deploy `npm run deploy:prod`

here my code:
nuxt.config.js
```
const pkg = require("./package.json")
module.exports = {
  mode: 'universal',
env: {
GOOGLE_TAG_MANAGER_ID: process.env.GOOGLE_TAG_MANAGER_ID,
  FACEBOOK_PIXEL_ID: process.env.FACEBOOK_PIXEL_ID,
},
  modules: [
    'nuxt-facebook-pixel-module',
    ['@nuxtjs/google-tag-manager', { id: process.env.GOOGLE_TAG_MANAGER_ID }],
  ],
  facebook: {
    track: 'PageView',
    pixelId: process.env.FACEBOOK_PIXEL_ID,
    disabled: false
  },
}
```
.env-cmdrc.js
```
  prod: {
    FACEBOOK_PIXEL_ID: 'xxxx',
    GOOGLE_TAG_MANAGER_ID: 'xxxx',
}
```

Error:
```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: The `pixelId` option is required.",
    "reason": {
        "errorType": "Error",
        "errorMessage": "The `pixelId` option is required.",
        "stack": [
            "Error: The `pixelId` option is required.",
            "    at ModuleContainer.facebookPixelModule (/var/task/node_modules/nuxt-facebook-pixel-module/lib/module.js:13:31)",
            "    at ModuleContainer.addModule (/var/task/node_modules/@nuxt/core/dist/core.js:215:34)",
            "    at /var/task/node_modules/@nuxt/utils/dist/utils.js:1803:43",
            "    at async ModuleContainer.ready (/var/task/node_modules/@nuxt/core/dist/core.js:43:5)",
            "    at async Nuxt._init (/var/task/node_modules/@nuxt/core/dist/core.js:685:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: The `pixelId` option is required.",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:310:20)",
        "    at processEmit [as emit] (/var/task/node_modules/signal-exit/index.js:161:32)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```

**Comment by wan2land** [comment]
**env-cmd** is a tool that simply enters environment variables into the program to be executed.

You need to set environment variables in the lambda environment to be actually executed.

check `serverless.yml`

```yaml
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    NODE_ENV: ${env:NODE_ENV}
    FACEBOOK_PIXEL_ID: ${env:FACEBOOK_PIXEL_ID}
    GOOGLE_TAG_MANAGER_ID: ${env:GOOGLE_TAG_MANAGER_ID}
```
