### ISSUE TITLE
I cannot call the api via axios

### ISSUE THREAD

**Issue by thenewspacesky5456** [wan2land/serverless-nuxt#86]
Hello @wan2land 
I cannot call the api via axios
**axios.js plugins**
```
import { showError } from '@/common/AppUtils.js'

export default function({ $axios, redirect, store, app }) {
  $axios.setHeader('Content-Type', 'application/json')
  $axios.onRequest((config) => {
    if (app.$auth.getToken('local')) {
      config.headers.common.Authorization = app.$auth.getToken('local')
    }
  })
  $axios.onError((error) => {
    const code = parseInt(error.response && error.response.status)
    if (code === 401) {
      app.$auth.logout()
    } else {
      showError(error.response.data.message)
    }
    return Promise.reject(error)
  })
}
```
**Index.vue**

```
  async asyncData({ app, $axios, error }) {
    try {
      // console.log(app.$device)
      const todaySuggestionProducts = await $axios.$get(
        '/products'
      )
```
**nuxt.config.js**

```
  axios: {
    baseURL: process.env.API_URL
  },
```

**Error:**
```
13:06:39
2020-04-28T13:06:39.174Z ba79c228-4fba-4e6e-af87-2bc4889d031c INFO TypeError: Cannot read property 'data' of undefined at server.js:1:595274 at server.js:1:593957 at processTicksAndRejections (internal/process/task_queues.js:97:5) at async asyncData (9b81432fb5e8a30cf197.js:1:32789)
2020-04-28T13:06:39.174Z	ba79c228-4fba-4e6e-af87-2bc4889d031c	INFO	TypeError: Cannot read property 'data' of undefined
    at server.js:1:595274
    at server.js:1:593957
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async asyncData (9b81432fb5e8a30cf197.js:1:32789)
```

**Comment by wan2land** [comment]
I want to see the full source of `asyncData`.

**Comment by wan2land** [comment]
```
      showError(error.response.data.message)
```

Is the `response.data` value `undefined`?

**Comment by thenewspacesky5456** [comment]
Hello @wan2land .
I think this issues related to baseURL
```
  async asyncData({ app, $axios, error }) {
    try {
      const todaySuggestionProducts = await $axios.$get(
        '/product/suggestion-today'
      )
   
      return {
        todaySuggestionProducts
      }
    } catch (err) {
      console.log(err)
      app.$sentry.captureException(err)
      error({ statusCode: 404, message: 'Post not found' })
    }
  },
```

**Comment by wan2land** [comment]
1. Make sure the API_URL value is set in the environment variable when it is built.
2. After deployment, check if the API_URL value is set in the Lambda environment variable.

https://github.com/wan2land/serverless-nuxt/issues/74#issuecomment-618218512

Check `.env-cmdrc.js`, `serverless.yml` - `provider.environment`, and `package.json` - `scripts`.
